name: my first workflow

on: 
  workflow_dispatch:
  push: tags

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "hello github actions"
          date