name: my first workflow

on: workflow_dispacth

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "hello github actions"
          date