name: my first workflow

on:
  push: 
    tags: 
      - v**

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "hello github actions"
          date